minimumReleaseAge: 1440
trustPolicy: no-downgrade
blockExoticSubdeps: true
verifyStoreIntegrity: true
strictStorePkgContentCheck: true
saveExact: true

overrides:
  fast-uri: '3.1.4'
  tmp: '0.2.7'
  uuid: '11.1.1'

allowBuilds:
  esbuild: true
