export const contextualHelpTopics = {
	fad: {
		label: 'Débit réellement restitué (FAD)',
		definition: 'Le FAD est le débit d’air libre effectivement délivré par le compresseur, associé à une pression et à des conditions de mesure.',
		influence: 'C’est ce débit, et non le débit aspiré, que CompatAir rapproche du besoin de l’outil.',
		location: 'Cherchez une courbe de débit, une fiche CAGI ou une valeur « air delivery / FAD » dans la documentation du modèle.',
		example: 'Exemple : 180 L/min à 7 bar. Une valeur à 0 bar ou un débit aspiré ne prouve pas ce débit à 7 bar.',
		missing: 'Sans FAD exploitable à la pression demandée, le verdict reste « données insuffisantes » et CompatAir propose des modèles mieux documentés.',
		glossaryHref: '/glossaire/#fad',
	},
	loadedPressure: {
		label: 'Pression en charge',
		definition: 'La pression en charge est mesurée au point d’usage pendant que l’air circule et que l’outil fonctionne.',
		influence: 'Une pression correcte à l’arrêt peut chuter dès que le débit traverse le flexible, les raccords et les filtres.',
		location: 'Placez un manomètre au plus près de l’outil et relevez la valeur pendant une séquence représentative.',
		example: 'Exemple : 7,5 bar au compresseur à l’arrêt, mais 6,1 bar à l’entrée de l’outil en fonctionnement.',
		missing: 'CompatAir signale la perte possible sans inventer sa valeur ; la vérification terrain reste à effectuer.',
		glossaryHref: '/glossaire/#pression-dynamique',
	},
	margin: {
		label: 'Réserve de débit',
		definition: 'La réserve est ajoutée au besoin calculé afin de distinguer la consommation publiée de la cible de dimensionnement.',
		influence: 'Elle augmente le débit cible sans modifier le besoin constructeur de l’outil.',
		location: 'Le réglage se trouve dans les options avancées. La valeur par défaut CompatAir est 25 % et reste modifiable.',
		example: 'Exemple : un besoin de 160 L/min avec 25 % de réserve donne une cible de 200 L/min.',
		missing: 'Si vous ne la modifiez pas, CompatAir conserve 25 % et l’affiche séparément dans la réponse.',
		glossaryHref: '/glossaire/#marge-compatair',
	},
	duration: {
		label: 'Durée de session',
		definition: 'La durée de session décrit le temps total prévu entre le début et la fin de l’usage, pas nécessairement un fonctionnement continu.',
		influence: 'Elle aide à confronter l’usage prévu au cycle de service publié du compresseur et à expliciter les limites temporelles.',
		location: 'Estimez une séquence réelle : opération, reprises et pauses comprises.',
		example: 'Exemple : 30 minutes d’intervention avec un outil utilisé environ 30 % du temps.',
		missing: 'Le calculateur utilise 30 minutes par défaut ; adaptez cette valeur dès que la session réelle est connue.',
		glossaryHref: '/glossaire/#duree-session',
	},
	frequency: {
		label: 'Fréquence d’utilisation',
		definition: 'La fréquence décrit la part de la session pendant laquelle un outil à débit continu est effectivement sollicité.',
		influence: 'Elle agit sur la demande moyenne et le contrôle du cycle de service, jamais sur le débit instantané publié de l’outil.',
		location: 'Observez une séquence représentative ou chronométrez le temps outil actif sur la durée totale.',
		example: 'Exemple : 9 minutes d’usage cumulé sur 30 minutes correspondent à 30 %.',
		missing: 'Choisissez une hypothèse explicite et prudente ; CompatAir la conserve comme donnée d’usage, distincte des données constructeur.',
		glossaryHref: '/glossaire/#frequence-utilisation',
	},
	hose: {
		label: 'Flexible et restrictions',
		definition: 'La longueur, le diamètre intérieur, les raccords et les filtres conditionnent la perte de pression entre la machine et l’outil.',
		influence: 'Un passage trop étroit ou trop long peut rendre insuffisante une configuration pourtant correcte à la sortie du compresseur.',
		location: 'Lisez le marquage du flexible et mesurez sa longueur totale, rallonges et raccordements inclus.',
		example: 'Exemple : 10 m de flexible avec 9 mm de diamètre intérieur, avant ajout des coupleurs.',
		missing: 'CompatAir ne calcule aucune perte silencieuse ; il demande une mesure en charge lorsque le réseau n’est pas caractérisé.',
		glossaryHref: '/glossaire/#flexible-air-comprime',
	},
	dutyCycle: {
		label: 'Cycle de service',
		definition: 'Le cycle de service est la part du temps pendant laquelle une machine peut fonctionner dans les conditions définies par son fabricant.',
		influence: 'Il limite la capacité moyenne soutenable même lorsque le débit instantané couvre le besoin.',
		location: 'Consultez la notice du modèle ; la période de référence et les conditions doivent accompagner le pourcentage.',
		example: 'Exemple : 50 % sur 10 minutes signifie au plus 5 minutes de marche dans cette période, selon les conditions publiées.',
		missing: 'CompatAir n’invente pas de cycle. La compatibilité continue ne peut pas être confirmée sur ce critère.',
		glossaryHref: '/glossaire/#cycle-service',
	},
	sourceQuality: {
		label: 'Qualité des sources',
		definition: 'Le libellé visible résume la complétude et la traçabilité des données utiles au verdict ; le grade technique reste disponible dans le détail.',
		influence: 'À verdict égal, une source constructeur complète est privilégiée par rapport à une fiche partielle ou indirecte.',
		location: 'Chaque fiche et chaque résultat indique la source, la date de vérification et les caractéristiques effectivement couvertes.',
		example: 'Exemple : une courbe FAD constructeur datée est plus exploitable qu’une valeur commerciale sans pression.',
		missing: 'Une donnée non sourcée n’est pas utilisée pour rendre un verdict positif ; la limite reste visible et actionnable.',
		glossaryHref: '/glossaire/#qualite-sources',
	},
} as const;

export type ContextualHelpTopic = keyof typeof contextualHelpTopics;
